name: Timlink-HS

services: 
  mongo:
    image: mongo:8
    container_name: timlink-mongo
    restart: unless-stopped
    # environment: 
      # MONGO_INITDB_ROOT_USERNAME:
      # MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
       - timlink-hs
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: timlink-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - timlink-hs  

  api:
    build:
     context: ./back
     dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./back/.env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started  
    volumes:
      - ./back:/app
      - /app/node_modules
    networks:
      - timlink-hs
    ports:
      - 3001:3001

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./front/.env
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - timlink-hs
    ports:
      - 3000:3000
    command: npm start -- --host
    depends_on:
      - api  

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - timlink-hs
    depends_on:
      - api
      - front

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  timlink-hs:
    driver: bridge